language: python

python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - pypy
  - pypy3

install:
    - pip install scrutinizer-ocular
    # Coveralls 4.0 doesn't support Python 3.2
    - if [ "$TRAVIS_PYTHON_VERSION" == "3.2" ]; then travis_retry pip install coverage==3.7.1; fi
    - if [ "$TRAVIS_PYTHON_VERSION" != "3.2" ]; then travis_retry pip install coverage; fi
before_script:
  - python setup.py install

script:
  - python run_tests.py
  - if [ "$TRAVIS_PYTHON_VERSION" = "3.4" ]; then coverage3 run run_tests.py;fi

after_script:
  - ocular --data-file ".coverage"
