language: python

python:
  - 3.2
  - 3.3
  - 3.4
  - pypy3

before_script:
  - ./setup.py install

script:
  - ./run_tests.py

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
